name: release

on:
 push:
   branches:
     - main

jobs:
  workshopUpload:
    runs-on: ubuntu-latest
    steps:
      - uses: m00nl1ght-dev/steam-workshop-deploy@v4
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
          path: build
          appId: 294100
          publishedFileId: 3810534416
