name: release

on:
 push:
   branches:
     - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: releaseFilename
        id: release
        run: |
          echo "releasezip=gravship_floodlights_$(echo $EPOCHSECONDS).zip"

      - name: createReleaseZip
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ${{ steps.release.outputs.releasezip }}
          exclusions: '/.git/* /Sources/* /AddOn/* /.github/* .git* *.pdb'
  
      - name: Extract zip for workshop upload
        env:
          ZIP_FILE: ${{ steps.release.outputs.releasezip }}
        run: |
          sudo apt-get install unzip
          mkdir ws-upload/
          unzip $ZIP_FILE -d ws-upload
    
      - name: workshopUpload
        uses: m00nl1ght-dev/steam-workshop-deploy@v4
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
          path: ws-upload
          appId: 294100
          publishedFileId: 3810534416
